In [1]:
import pandas as pd

In [2]:
pwd

'/Users/ming/Downloads/Tensorflow-Bootcamp-master'

In [12]:
df = pd.read_csv('proxylist.csv')

In [13]:
df

    199.241.144.184  60099  61336  ganjiayan  Bi7jU9TI
0   199.241.144.187  60099  61336  ganjiayan  Bi7jU9TI
1   199.241.144.188  60099  61336  ganjiayan  Bi7jU9TI
2   199.241.144.189  60099  61336  ganjiayan  Bi7jU9TI
3   199.241.144.135  60099  61336  ganjiayan  Bi7jU9TI
4   199.241.144.137  60099  61336  ganjiayan  Bi7jU9TI
5     23.228.77.198  60099  61336  ganjiayan  Bi7jU9TI
6     23.228.77.200  60099  61336  ganjiayan  Bi7jU9TI
7     23.228.77.201  60099  61336  ganjiayan  Bi7jU9TI
8     23.228.77.202  60099  61336  ganjiayan  Bi7jU9TI
9     23.228.77.203  60099  61336  ganjiayan  Bi7jU9TI
10    23.228.77.207  60099  61336  ganjiayan  Bi7jU9TI
11    23.228.77.208  60099  61336  ganjiayan  Bi7jU9TI
12    23.228.77.211  60099  61336  ganjiayan  Bi7jU9TI
13    23.228.77.214  60099  61336  ganjiayan  Bi7jU9TI
14    23.228.77.215  60099  61336  ganjiayan  Bi7jU9TI
15    23.228.77.217  60099  61336  ganjiayan  Bi7jU9TI
16    23.228.77.218  60099  61336  ganjiayan  Bi7jU9TI
17    23.228.77.219  60099  61336  ganjiayan  Bi7jU9TI
18    23.228.77.221  60099  61336  ganjiayan  Bi7jU9TI
19    23.228.77.224  60099  61336  ganjiayan  Bi7jU9TI
20    23.228.77.225  60099  61336  ganjiayan  Bi7jU9TI
21    23.228.77.227  60099  61336  ganjiayan  Bi7jU9TI
22    23.228.77.228  60099  61336  ganjiayan  Bi7jU9TI
23    23.228.77.229  60099  61336  ganjiayan  Bi7jU9TI
24    23.228.77.232  60099  61336  ganjiayan  Bi7jU9TI
25    23.228.77.237  60099  61336  ganjiayan  Bi7jU9TI
26    23.228.77.239  60099  61336  ganjiayan  Bi7jU9TI
27    23.228.77.244  60099  61336  ganjiayan  Bi7jU9TI
28    23.228.77.245  60099  61336  ganjiayan  Bi7jU9TI
29    23.228.77.253  60099  61336  ganjiayan  Bi7jU9TI

In [20]:
df[['199.241.144.184','ganjiayan']]

    199.241.144.184  ganjiayan
0   199.241.144.187  ganjiayan
1   199.241.144.188  ganjiayan
2   199.241.144.189  ganjiayan
3   199.241.144.135  ganjiayan
4   199.241.144.137  ganjiayan
5     23.228.77.198  ganjiayan
6     23.228.77.200  ganjiayan
7     23.228.77.201  ganjiayan
8     23.228.77.202  ganjiayan
9     23.228.77.203  ganjiayan
10    23.228.77.207  ganjiayan
11    23.228.77.208  ganjiayan
12    23.228.77.211  ganjiayan
13    23.228.77.214  ganjiayan
14    23.228.77.215  ganjiayan
15    23.228.77.217  ganjiayan
16    23.228.77.218  ganjiayan
17    23.228.77.219  ganjiayan
18    23.228.77.221  ganjiayan
19    23.228.77.224  ganjiayan
20    23.228.77.225  ganjiayan
21    23.228.77.227  ganjiayan
22    23.228.77.228  ganjiayan
23    23.228.77.229  ganjiayan
24    23.228.77.232  ganjiayan
25    23.228.77.237  ganjiayan
26    23.228.77.239  ganjiayan
27    23.228.77.244  ganjiayan
28    23.228.77.245  ganjiayan
29    23.228.77.253  ganjiayan

parsing a list

In [21]:
df['199.241.144.184'].max()

'23.228.77.253'

In [22]:
df.describe()

         60099    61336
count     30.0     30.0
mean   60099.0  61336.0
std        0.0      0.0
min    60099.0  61336.0
25%    60099.0  61336.0
50%    60099.0  61336.0
75%    60099.0  61336.0
max    60099.0  61336.0

In [26]:
myfilter = df['60099'] > 0

In [27]:
df[myfilter]

    199.241.144.184  60099  61336  ganjiayan  Bi7jU9TI
0   199.241.144.187  60099  61336  ganjiayan  Bi7jU9TI
1   199.241.144.188  60099  61336  ganjiayan  Bi7jU9TI
2   199.241.144.189  60099  61336  ganjiayan  Bi7jU9TI
3   199.241.144.135  60099  61336  ganjiayan  Bi7jU9TI
4   199.241.144.137  60099  61336  ganjiayan  Bi7jU9TI
5     23.228.77.198  60099  61336  ganjiayan  Bi7jU9TI
6     23.228.77.200  60099  61336  ganjiayan  Bi7jU9TI
7     23.228.77.201  60099  61336  ganjiayan  Bi7jU9TI
8     23.228.77.202  60099  61336  ganjiayan  Bi7jU9TI
9     23.228.77.203  60099  61336  ganjiayan  Bi7jU9TI
10    23.228.77.207  60099  61336  ganjiayan  Bi7jU9TI
11    23.228.77.208  60099  61336  ganjiayan  Bi7jU9TI
12    23.228.77.211  60099  61336  ganjiayan  Bi7jU9TI
13    23.228.77.214  60099  61336  ganjiayan  Bi7jU9TI
14    23.228.77.215  60099  61336  ganjiayan  Bi7jU9TI
15    23.228.77.217  60099  61336  ganjiayan  Bi7jU9TI
16    23.228.77.218  60099  61336  ganjiayan  Bi7jU9TI
17    23.228.77.219  60099  61336  ganjiayan  Bi7jU9TI
18    23.228.77.221  60099  61336  ganjiayan  Bi7jU9TI
19    23.228.77.224  60099  61336  ganjiayan  Bi7jU9TI
20    23.228.77.225  60099  61336  ganjiayan  Bi7jU9TI
21    23.228.77.227  60099  61336  ganjiayan  Bi7jU9TI
22    23.228.77.228  60099  61336  ganjiayan  Bi7jU9TI
23    23.228.77.229  60099  61336  ganjiayan  Bi7jU9TI
24    23.228.77.232  60099  61336  ganjiayan  Bi7jU9TI
25    23.228.77.237  60099  61336  ganjiayan  Bi7jU9TI
26    23.228.77.239  60099  61336  ganjiayan  Bi7jU9TI
27    23.228.77.244  60099  61336  ganjiayan  Bi7jU9TI
28    23.228.77.245  60099  61336  ganjiayan  Bi7jU9TI
29    23.228.77.253  60099  61336  ganjiayan  Bi7jU9TI

combile those two filter steps into one line: df[myfilter = df['60099'] > 0]